### PR TITLE
fix(logger): no longer detects duplicate object as circular

### LINKED ISSUE #1510: Log incorrectly prints [Circular] for object property when it shares reference with another property in the same object
### [REQUIRED] Version info

**node:** 18.19.0

**firebase-functions:** 4.6.0

**firebase-tools:** 12.9.1

**firebase-admin:** 11.11.0

### [REQUIRED] Test case

My function is the following:
```ts
import { onCall } from "firebase-functions/v2/https";
import { logger } from "firebase-functions/v2";

export const testFunction = onCall(
  {
    region: "europe-west1",
  },
  (request) => {
    const commonData = { foo: "bar" }
    const obj1 = {
      data: commonData,

    }
    const obj2 = {
      data: commonData,

    }
    logger.debug("TEST 1", { obj1, obj2 })
  }
);

```

### [REQUIRED] Steps to reproduce

- Call the function
- View the logs

### [REQUIRED] Expected behavior

When calling the function (e.g. locally) it should log with the json payload:
```json
{
  "obj1": { "data": { "foo": "bar" } },
  "obj2": { "data": { "foo": "bar" } },
  "severity": "DEBUG",
  "message": "TEST 1"
}

```

### [REQUIRED] Actual behavior

Instead it prints the following payload:
```json
{
  "obj1": { "data": { "foo": "bar" } },
  "obj2": { "data": "[Circular]" },
  "severity": "DEBUG",
  "message": "TEST 1"
}

```

### Were you able to successfully deploy your functions?

Yes, I had the same issue when viewing the logs in the log explorer.

### PR DESCRIPTION
**Pull request by CorieW**
Resolves #1510

### CODE REVIEW

File: src/logger/index.ts [hunk 1]
```diff
@@ -56,28 +56,25 @@ function removeCircular(obj: any, refs: any[] = []): any {
...
   }
-  // If the object defines its own toJSON, prefer that.
-  if (obj.toJSON) {
+  // If the object defines its own toJSON method, use it.
+  if (obj.toJSON && typeof obj.toJSON === "function") {
     return obj.toJSON();
   }
-  if (refs.includes(obj)) {
+  // Only check for circularity among ancestors in the recursion stack.
+  if (refs.indexOf(obj) !== -1) {
```
Comment (cabljac) [inline src/logger/index.ts:64]: why change to indexOf? isn't this functionally the same?

File: src/logger/index.ts [hunk 2]
```diff
@@ -56,28 +56,25 @@ function removeCircular(obj: any, refs: any[] = []): any {
...
-    if (refs.includes(obj[k])) {
-      returnObj[k] = "[Circular]";
-    } else {
-      returnObj[k] = removeCircular(obj[k], refs);
+  // Add the current object to the recursion stack.
+  refs.push(obj);
+
+  const returnObj: any = Array.isArray(obj) ? [] : {};
+  for (const key in obj) {
+    if (Object.prototype.hasOwnProperty.call(obj, key)) {
```
Comment (cabljac) [inline src/logger/index.ts:72]: We are no longer doing this logic here:

```
    if (refs.includes(obj[k])) {
      returnObj[k] = "[Circular]";
    } else {
```

Makes the code slightly less efficient?

Maybe more readable, but feels like we're changing how the code works a bit?

**Review by cabljac — CHANGES_REQUESTED** [review]
generally lgtm, couple of questions though

File: src/logger/index.ts (hunk 1 above)
Comment (CorieW) [reply src/logger/index.ts:64]: oh yeah 😆

Comment (CorieW) [inline src/logger/index.ts:64]:
```suggestion
  if (refs.includes(obj)) {
```

File: src/logger/index.ts [hunk 3]
```diff
@@ -56,28 +56,32 @@ function removeCircular(obj: any, refs: any[] = []): any {
...
-  } else {
-    returnObj = {};
+    returnObj = obj.map((item) => removeCircular(item, refs));
   }
-  for (const k in obj) {
-    if (refs.includes(obj[k])) {
-      returnObj[k] = "[Circular]";
-    } else {
-      returnObj[k] = removeCircular(obj[k], refs);
+  // If the object is a Map, run circular check on each key and value.
```
Comment (cabljac) [inline src/logger/index.ts:75]: nitpick on the comment but we're not dealing with a js "Map" here, just an object

**Review by cabljac — APPROVED** [review]
lgtm!
